# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=50)),
                ('book_author', models.CharField(default='anonymous', max_length=50)),
                ('book_illustrator', models.CharField(blank=True, default='', max_length=50)),
                ('book_publisher', models.CharField(default='', max_length=50)),
                ('book_datePublished', models.DateTimeField(blank=True, default='')),
                ('book_numOfPages', models.IntegerField(blank=True, default='')),
                ('book_hardback', models.BooleanField(default=False)),
                ('book_retailPrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default='')),
                ('order_numOfItems', models.IntegerField(default='')),
                ('order_totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order_shippingAddress', models.CharField(default='In-Store purchase', max_length=100)),
                ('order_shippingZipCode', models.IntegerField(default='')),
                ('order_paid', models.BooleanField(default=False)),
                ('order_shipped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=70)),
                ('phone_num', models.IntegerField(blank=True, default=0)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.IntegerField(blank=True, default=0)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AK', max_length=2)),
                ('card_num', models.IntegerField(blank=True, default=0)),
                ('card_name', models.CharField(blank=True, max_length=30)),
                ('exp_month', models.CharField(choices=[('12', 'December'), ('11', 'November'), ('10', 'October'), ('9', 'September'), ('8', 'August'), ('7', 'July'), ('6', 'June'), ('5', 'May'), ('4', 'April'), ('3', 'March'), ('2', 'February'), ('1', 'January')], default=12, max_length=2)),
                ('exp_year', models.IntegerField(default=2017)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_name', models.CharField(max_length=30)),
                ('review_content', models.CharField(blank=True, max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_itemName', models.CharField(default='', max_length=50)),
                ('cart_itemPrice', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('cart_shippingPrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_salesTax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_numOfItems', models.IntegerField(default=0)),
                ('cart_subTotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_discounts', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('cart_grandTotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
